export 'package:faiznikah/src/app/authentication/login_register_page.dart';
export 'package:faiznikah/src/app/home/screens/all_profile.dart';
export 'package:faiznikah/src/app/home/screens/home.dart';
export 'package:faiznikah/src/app/profile/screens/profile_creaton_page.dart';
export 'package:faiznikah/src/app/profile/screens/profile_details.dart';
export 'package:faiznikah/src/app/static/screens/about.dart';
export 'package:faiznikah/src/app/static/screens/privacy_policy.dart';
/* export 'package:faiznikah/src/app/authentication/';
export 'package:faiznikah/src/app/authentication/';
export 'package:faiznikah/src/app/authentication/';
export 'package:faiznikah/src/app/authentication/';
export 'package:faiznikah/src/app/authentication/';
export 'package:faiznikah/src/app/authentication/';
export 'package:faiznikah/src/app/authentication/';
export 'package:faiznikah/src/app/authentication/';
export 'package:faiznikah/src/app/authentication/';
export 'package:faiznikah/src/app/authentication/';
export 'package:faiznikah/src/app/authentication/';
export 'package:faiznikah/src/app/authentication/';
export 'package:faiznikah/src/app/authentication/'; */